# Generated by Django 5.1.1 on 2024-09-22 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Supplier creation', 'Supplier creation'), ('PO creation', 'PO creation'), ('NDA', 'NDA'), ('Supplier Assist', 'Supplier Assist'), ('Other request', 'Other request')], max_length=20)),
                ('po_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Canceled', 'Canceled')], default='Not Started', max_length=20)),
                ('subject', models.CharField(max_length=25)),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object', models.CharField(editable=False, max_length=255)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('comments', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.buyer')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.requester')),
            ],
        ),
    ]
