# Generated by Django 5.1.1 on 2024-09-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='created_by',
            new_name='user',
        ),
    ]
