# Generated by Django 5.1 on 2024-10-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_rename_created_by_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Supplier creation', 'Supplier creation'), ('PO creation', 'PO creation'), ('NDA', 'NDA'), ('Supplier Assist', 'Supplier Assist'), ('Other request', 'Other request'), ('PO modification', 'PO modification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
